language: ruby
sudo: required
rvm:
  - 2.0.0
env:
  - VIM_VERSION=7.3
  - VIM_VERSION=7.4
before_install:
  - cd ~; wget ftp://ftp.vim.org/pub/vim/unix/vim-${VIM_VERSION}.tar.bz2
  - tar xf vim-${VIM_VERSION}.tar.bz2 -C ~/vim --strip-components=1; cd vim
  - ./configure --prefix=$HOME
  - make && sudo make install
  - which vim
  - export PATH=$HOME:$PATH
  - which vim
script: rake ci
notifications:
  email: false

