language: ruby
sudo: required
rvm:
  - 2.0.0
env:
  - VIM_VERSION=7.3
  - VIM_VERSION=7.4
before_install:
  - sudo apt-get update
  - sudo apt-get install vim=$VIM_VERSION
script: rake ci
notifications:
  email: false

